#!/usr/bin/env bash

### CITS4407 assignment 1: tobacco_nation
# Written by Erica Kong. UWA student ID:24071068

### Usage of this program 
# This program takes exactly 3 arguments:
# 1. The name of a database formatted like WHO_tobacco_control_tonly.csv
# 2. The three-letter ISO standard identifier for a country (as used in the database) OR a year
# 3. The sex of the smoking population: Female or Male (We will not be using Both, which is the mean of the Famale and Male smoking rates).
Usage(){
    echo "Usage: tobacco_nation <csv data file>  < year | country code >  < Male | Female >"
}

### Conditional control of this program 
# If there is no argument in the user-input
if [ $# -eq 0 ] 
then
    Usage
    exit 1
    
# If the number of argument is not three 
elif [ $# -ne 3 ]
then
    echo "$0: this program requires three arguments"
    Usage
    exit 1

# If the number of argument is three 
else
    # If the file does not exist or has zero length
    if !(test -s "$1")    # or use : if [ ! -s "$1" ]
    then      
        echo "The named input file ${1} does not exist or has zero length"
    # If the file exist and has length
    else     
        # Sorting data and giving the row of desired result to this variable
        res_row=$(grep $2 $1 | grep $3 | sort -t, -k 7,7 -nr | head -1 )
    
        # The maximum percentage of tobacco
        maxPC=$(echo "$res_row"| cut -d ',' -f7)
        
        # The country code
        country_code=$(echo "$res_row"| cut -d ',' -f3)
        # The country name
        country_name=$(echo "$res_row"| cut -d ',' -f4)
        # The year
        year=$(echo "$res_row"| cut -d ',' -f5) 
        # Current year
        # current_year=$(date | cut -d ' ' -f4) # this command works different in linux
        current_year="2024"
        
        # If the result is empty
        if !(test -n "$maxPC")   # or use: if [ ! -n "$maxPC" ]
        then 
            echo "$0: No matching data for your input"
            exit 1
        # If the result is not empty, then 
        else    
            # If the second argument is year (a number)
            if [[ "$2" =~ ^[0-9]+$ ]] 
            then
                # If the input number is not the year number e.g. 202
                if [ $2 -ne $year ]
                then
                    echo "$0: No matching data for your input"
                    exit 1
                
                else
                    # Compare current year and the year in the dataset
                    # If the year is in the past
                    if [ $2 -lt $current_year ]
                    then
                        echo "The global maximum percentage of ${3} tobacco users in ${2} was in ${country_name}(${country_code}) at ${maxPC}"
                    # If the year is in the future
                    else
                        echo "The global maximum percentage of ${3} tobacco users in ${2} is predicted to be in ${country_name}(${country_code}) at ${maxPC}" 
                    fi
                fi
            # If the second argument is country code   
            else
                echo "The global maximum percentage of ${3} tobacco users for ${country_name}(${2}) was ${maxPC} in ${year}"  
            
            fi    
        fi    
    fi            
fi


